[2024-07-21 03:41:05,446] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-31T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,539] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-31T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,540] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,542] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-07-21 03:41:05,543] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,633] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2021-07-31T00:00:00+00:00
[2024-07-21 03:41:05,664] {standard_task_runner.py:52} INFO - Started process 192 to run task
[2024-07-21 03:41:05,672] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_task', 'load_from_mysql', '2021-07-31T00:00:00+00:00', '--job-id', '156', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ELT.py', '--cfg-path', '/tmp/tmpz12jd4pu', '--error-file', '/tmp/tmp9p51u9en']
[2024-07-21 03:41:05,678] {standard_task_runner.py:77} INFO - Job 156: Subtask load_from_mysql
[2024-07-21 03:41:34,848] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2024-07-21 03:41:51,167] {local_task_job.py:194} WARNING - Recorded pid 279 does not match the current pid 192
[2024-07-21 03:41:51,251] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 192
[2024-07-21 03:41:51,319] {process_utils.py:66} INFO - Process psutil.Process(pid=192, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='03:41:05') (192) terminated with exit code Negsignal.SIGTERM
