[2024-07-21 03:41:05,464] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-21T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,542] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-21T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,543] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,545] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-07-21 03:41:05,549] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,600] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2021-07-21T00:00:00+00:00
[2024-07-21 03:41:05,644] {standard_task_runner.py:52} INFO - Started process 190 to run task
[2024-07-21 03:41:05,678] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_task', 'load_from_mysql', '2021-07-21T00:00:00+00:00', '--job-id', '166', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ELT.py', '--cfg-path', '/tmp/tmp60j7lu_e', '--error-file', '/tmp/tmp_8tw5ms4']
[2024-07-21 03:41:05,691] {standard_task_runner.py:77} INFO - Job 166: Subtask load_from_mysql
[2024-07-21 03:41:48,574] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2024-07-21 03:41:51,244] {local_task_job.py:194} WARNING - Recorded pid 262 does not match the current pid 190
[2024-07-21 03:41:51,283] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 190
[2024-07-21 03:41:51,332] {process_utils.py:66} INFO - Process psutil.Process(pid=190, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='03:41:05') (190) terminated with exit code Negsignal.SIGTERM
